// <auto-generated />
namespace Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IsForSelfSignUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsForSelfSignUp));
        
        string IMigrationMetadata.Id
        {
            get { return "201505070636269_IsForSelfSignUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
