// <auto-generated />
namespace Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Icon_IconSet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Icon_IconSet));
        
        string IMigrationMetadata.Id
        {
            get { return "201612062203307_Icon_IconSet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
