// <auto-generated />
namespace Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AppendToDefaultIconSet_ORP914 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppendToDefaultIconSet_ORP914));
        
        string IMigrationMetadata.Id
        {
            get { return "201702162232152_AppendToDefaultIconSet_ORP914"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
