// <auto-generated />
namespace Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Legal_Disclaimer_ORP_912 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Legal_Disclaimer_ORP_912));
        
        string IMigrationMetadata.Id
        {
            get { return "201702150633318_Legal_Disclaimer_ORP_912"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
