// <auto-generated />
namespace Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NotificationInterval_ORP1146 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NotificationInterval_ORP1146));
        
        string IMigrationMetadata.Id
        {
            get { return "201707190920214_NotificationInterval_ORP-1146"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
