// <auto-generated />
namespace Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EnableTrainingActivityLoggingModule_ORP_1056 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnableTrainingActivityLoggingModule_ORP_1056));
        
        string IMigrationMetadata.Id
        {
            get { return "201704120647279_EnableTrainingActivityLoggingModule_ORP_1056"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
