// <auto-generated />
namespace Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ORP1256_PackageToBundle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ORP1256_PackageToBundle));
        
        string IMigrationMetadata.Id
        {
            get { return "201805152003360_ORP-1256_PackageToBundle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
