// <auto-generated />
namespace Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ORP1305_DashboardVideoQuote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ORP1305_DashboardVideoQuote));
        
        string IMigrationMetadata.Id
        {
            get { return "201810252253036_ORP-1305_DashboardVideoQuote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
