// <auto-generated />
namespace Data.EF.Customer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ExpiryNotificationSentOn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpiryNotificationSentOn));
        
        string IMigrationMetadata.Id
        {
            get { return "201412031228095_ExpiryNotificationSentOn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
