// <auto-generated />
namespace Data.EF.Customer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ManyUsersToManyTrainingActivities_ORP1119 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManyUsersToManyTrainingActivities_ORP1119));
        
        string IMigrationMetadata.Id
        {
            get { return "201705151119050_ManyUsersToManyTrainingActivities_ORP-1119"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
