// <auto-generated />
namespace Data.EF.Customer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlaybookPreviewType_ORP1040 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlaybookPreviewType_ORP1040));
        
        string IMigrationMetadata.Id
        {
            get { return "201703231139122_PlaybookPreviewType_ORP1040"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
