// <auto-generated />
namespace Data.EF.Customer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ORP1252_AssignedDocument_DocumentUsage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ORP1252_AssignedDocument_DocumentUsage));
        
        string IMigrationMetadata.Id
        {
            get { return "201806081010526_ORP-1252_AssignedDocument_DocumentUsage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
