// <auto-generated />
namespace Data.EF.Customer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ORP1238_PolicyResponse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ORP1238_PolicyResponse));
        
        string IMigrationMetadata.Id
        {
            get { return "201808060830385_ORP-1238_PolicyResponse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
