// <auto-generated />
namespace Data.EF.Customer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addIsrecurring_coloumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIsrecurring_coloumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202002030822105_addIsrecurring_coloumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
