// <auto-generated />
namespace Data.EF.Customer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_section_option_in_TestQuestionTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_section_option_in_TestQuestionTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202203161238469_added_section_option_in_TestQuestionTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
