// <auto-generated />
namespace Data.EF.Customer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_TestChapterUserResult : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_TestChapterUserResult));
        
        string IMigrationMetadata.Id
        {
            get { return "202203180721196_add_TestChapterUserResult"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
