// <auto-generated />
namespace Data.EF.Customer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_MemoChapterUserResult_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_MemoChapterUserResult_add));
        
        string IMigrationMetadata.Id
        {
            get { return "202203171827265_add_MemoChapterUserResult_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
