// <auto-generated />
namespace Data.EF.Customer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateed_Conditinoaltable_foreignKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateed_Conditinoaltable_foreignKey));
        
        string IMigrationMetadata.Id
        {
            get { return "202203220829351_updateed_Conditinoaltable_foreignKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
